swagger: "2.0"
info:
  version: "0.1"
  title: Santorini online
  license:
    name: WTF
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json

paths:
  /games:
    post:
      summary: creates a new
      responses:
        "201":
          summary: The game was created.
          schema:
            - $ref: "#/descriptions/game"

  /games/{gameID}:
    get:
      summary: returns the current state of the game.
      parameters:
        - name: gameID
          in: path
          description: The ID of the game
          required: true
          type: string
          format: uuid
      responses:
        "200":
          summary: OK
          schema:
            - $ref: "#/descriptions/game"
        404:
          summary: Game not found

  /games/{gameID}/play/{playerID}:
    post:
      summary: play for this player
      requestBody:
        description: The action of one player's turn
          required: true
          content:
            application/json:
              schema:
                - $ref: "#/descriptions/playAction"
      responses:
        200:
          summary: Next move accepted.
        423:
          summary: Not your turn.

descriptions:
  game:
    required: [gameID]
    properties:
      gameID: ID of the game
      nextPlayer: ID of the next player
      secondPlayer: ID of the opponent
      board:
        type: object
        properties:
          squares:
            type: array
            items:
              type: int
          pawns:
            type: array
            items:
              $ref: "#/descriptions/pawn"

  pawn:
    properties:
      pawnID: man or woman
      position:
        type: object
        properties:
          x: int
          y: int

  playAction:
    required: [action,position]
    properties:
      action:
        type: string
        enum: [move,build]
      position:
        type: object
        properties:
          x: int
          y: int
      pawn:
        type: string
        enum:
          - "man"
          - "woman"
